/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/coda/vehicle/PerceptionSomeIPDeployment.hpp>

namespace v1 {
namespace coda {
namespace vehicle {
namespace Perception_ {

// Type-specific deployments
GearStateDeployment_t GearStateDeployment(32, false);
UltrasonicNoDeployment_t UltrasonicNoDeployment(32, false);
DoorPosDeployment_t DoorPosDeployment(32, false);
DoorStateDeployment_t DoorStateDeployment(32, false);
::v1::coda::vehicle::Perception_::S_DoorStateDeployment_t S_DoorStateDeployment(0, &::v1::coda::vehicle::Perception_::DoorPosDeployment, &::v1::coda::vehicle::Perception_::DoorStateDeployment);
::v1::coda::vehicle::Perception_::S_UltrasonicStateDeployment_t S_UltrasonicStateDeployment(0, &::v1::coda::vehicle::Perception_::UltrasonicNoDeployment, static_cast< CommonAPI::EmptyDeployment* >(nullptr));

// Attribute-specific deployments

// Argument-specific deployment
CommonAPI::SomeIP::ArrayDeployment< ::v1::coda::vehicle::Perception_::S_DoorStateDeployment_t > requestAllDoorsStates_doorStateDeployment(&::v1::coda::vehicle::Perception_::S_DoorStateDeployment, 0, 0, 4);
CommonAPI::SomeIP::ArrayDeployment< ::v1::coda::vehicle::Perception_::S_UltrasonicStateDeployment_t > requestAllUltrasonicValues_ultrasonicStatesDeployment(&::v1::coda::vehicle::Perception_::S_UltrasonicStateDeployment, 0, 0, 4);

// Broadcast-specific deployments
CommonAPI::SomeIP::ArrayDeployment< ::v1::coda::vehicle::Perception_::S_DoorStateDeployment_t > multiDoorNotify_doorStateDeployment(&::v1::coda::vehicle::Perception_::S_DoorStateDeployment, 0, 0, 4);
CommonAPI::SomeIP::ArrayDeployment< ::v1::coda::vehicle::Perception_::S_UltrasonicStateDeployment_t > notifyMultiUltrasonic_ultrasonicStatesDeployment(&::v1::coda::vehicle::Perception_::S_UltrasonicStateDeployment, 0, 0, 4);

} // namespace Perception_
} // namespace vehicle
} // namespace coda
} // namespace v1
