/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */

#ifndef V1_CODA_VEHICLE_Perception_SOMEIP_DEPLOYMENT_HPP_
#define V1_CODA_VEHICLE_Perception_SOMEIP_DEPLOYMENT_HPP_


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace coda {
namespace vehicle {
namespace Perception_ {

// Interface-specific deployment types
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> GearStateDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> UltrasonicNoDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> DoorPosDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> DoorStateDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    ::v1::coda::vehicle::Perception_::DoorPosDeployment_t,
    ::v1::coda::vehicle::Perception_::DoorStateDeployment_t
> S_DoorStateDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    ::v1::coda::vehicle::Perception_::UltrasonicNoDeployment_t,
    CommonAPI::EmptyDeployment
> S_UltrasonicStateDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> CoordinatesDeployment_t;

// Type-specific deployments
COMMONAPI_EXPORT extern GearStateDeployment_t GearStateDeployment;
COMMONAPI_EXPORT extern UltrasonicNoDeployment_t UltrasonicNoDeployment;
COMMONAPI_EXPORT extern DoorPosDeployment_t DoorPosDeployment;
COMMONAPI_EXPORT extern DoorStateDeployment_t DoorStateDeployment;
COMMONAPI_EXPORT extern ::v1::coda::vehicle::Perception_::S_DoorStateDeployment_t S_DoorStateDeployment;
COMMONAPI_EXPORT extern ::v1::coda::vehicle::Perception_::S_UltrasonicStateDeployment_t S_UltrasonicStateDeployment;

// Attribute-specific deployments

// Argument-specific deployment
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< ::v1::coda::vehicle::Perception_::S_DoorStateDeployment_t > requestAllDoorsStates_doorStateDeployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< ::v1::coda::vehicle::Perception_::S_UltrasonicStateDeployment_t > requestAllUltrasonicValues_ultrasonicStatesDeployment;

// Broadcast-specific deployments
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< ::v1::coda::vehicle::Perception_::S_DoorStateDeployment_t > multiDoorNotify_doorStateDeployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< ::v1::coda::vehicle::Perception_::S_UltrasonicStateDeployment_t > notifyMultiUltrasonic_ultrasonicStatesDeployment;

} // namespace Perception_
} // namespace vehicle
} // namespace coda
} // namespace v1

#endif // V1_CODA_VEHICLE_Perception_SOMEIP_DEPLOYMENT_HPP_
