/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_CODA_VEHICLE_IVI_HPP_
#define V1_CODA_VEHICLE_IVI_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace coda {
namespace vehicle {

class IVI {
public:
    virtual ~IVI() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
    
    struct Theme : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            LIGHT = 0,
            DARK = 1
        };
    
        Theme()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::LIGHT)) {}
        Theme(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::LIGHT):
                case static_cast< uint8_t>(Literal::DARK):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const Theme &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const Theme &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const Theme &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const Theme &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const Theme &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const Theme &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::LIGHT): return "LIGHT";
            case static_cast< uint8_t>(Literal::DARK): return "DARK";
            default: return "UNDEFINED";
            }
        }
    };
};

const char* IVI::getInterface() {
    return ("coda.vehicle.IVI:v1_0");
}

CommonAPI::Version IVI::getInterfaceVersion() {
    return CommonAPI::Version(1, 0);
}


} // namespace vehicle
} // namespace coda
} // namespace v1

namespace CommonAPI {
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_CODA_VEHICLE_IVI_HPP_
