/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_CODA_VEHICLE_IVI_PROXY_BASE_HPP_
#define V1_CODA_VEHICLE_IVI_PROXY_BASE_HPP_

#include <v1/coda/vehicle/IVI.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <cstdint>
#include <vector>

#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace coda {
namespace vehicle {

class IVIProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::Event<
        ::v1::coda::vehicle::IVI::Theme
    > NotifyThemeChangeEvent;

    typedef std::function<void(const CommonAPI::CallStatus&, const IVI::Theme&)> RequestThemeAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&)> ChangeThemeAsyncCallback;

    virtual NotifyThemeChangeEvent& getNotifyThemeChangeEvent() = 0;
    virtual void requestTheme(CommonAPI::CallStatus &_internalCallStatus, IVI::Theme &_theme, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> requestThemeAsync(RequestThemeAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void changeTheme(IVI::Theme _theme, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> changeThemeAsync(const IVI::Theme &_theme, ChangeThemeAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace vehicle
} // namespace coda
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_CODA_VEHICLE_IVI_PROXY_BASE_HPP_
