/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/coda/vehicle/IVISomeIPStubAdapter.hpp>
#include <v1/coda/vehicle/IVI.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace coda {
namespace vehicle {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createIVISomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< IVISomeIPStubAdapter<::v1::coda::vehicle::IVIStub>>(_address, _connection, _stub);
}

void initializeIVISomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:coda.vehicle.IVI:v1_0:coda.vehicle.IVI",
         0x1236, 0x567a, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        "coda.vehicle.IVI:v1_0",
        &createIVISomeIPStubAdapter);
}

INITIALIZER(registerIVISomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeIVISomeIPStubAdapter);
}

} // namespace vehicle
} // namespace coda
} // namespace v1
